#!/usr/bin/env bash
# Generate third-party package-manager manifests from a release `checksums.txt`.
#
# Produces, in the output directory:
#   bbr.rb              Homebrew formula (macOS + Linux)
#   bbr.json            Scoop manifest (Windows)
#   winget/*.yaml       winget manifests (Windows)
#
# The inputs are the release's own checksums, so a manifest can never advertise
# a digest that does not match the published archive.
#
# Usage:
#   scripts/gen-packages.sh <version> <checksums.txt> <out-dir>
# Example:
#   scripts/gen-packages.sh 0.2.5 checksums.txt dist/packages
set -euo pipefail

VERSION="${1:?usage: gen-packages.sh <version> <checksums.txt> <out-dir>}"
CHECKSUMS="${2:?usage: gen-packages.sh <version> <checksums.txt> <out-dir>}"
OUT="${3:?usage: gen-packages.sh <version> <checksums.txt> <out-dir>}"

# Accept both `0.2.5` and `v0.2.5`.
VERSION="${VERSION#v}"
TAG="v${VERSION}"

REPO="themankindproject/bbr"
HOMEPAGE="https://github.com/${REPO}"
BASE_URL="${HOMEPAGE}/releases/download/${TAG}"

[ -f "$CHECKSUMS" ] || { echo "error: no such checksums file: $CHECKSUMS" >&2; exit 1; }
mkdir -p "$OUT/winget"

# ---- read the checksums into variables -------------------------------------
# Look up by exact basename. A missing entry is a hard error: shipping a
# manifest with an empty or wrong hash would fail every user's install.
digest_for() {
  local asset="$1" hash
  hash="$(awk -v want="$asset" '
    { name = $2; sub(/^\*/, "", name) }
    name == want { print $1; exit }
  ' "$CHECKSUMS")"
  if [ -z "$hash" ]; then
    echo "error: checksums.txt has no entry for ${asset}" >&2
    echo "  available:" >&2
    awk '{ name = $2; sub(/^\*/, "", name); print "    " name }' "$CHECKSUMS" >&2
    return 1
  fi
  printf '%s' "$hash"
}

MAC_ARM_SHA="$(digest_for bbr-aarch64-apple-darwin.tar.gz)"
MAC_X86_SHA="$(digest_for bbr-x86_64-apple-darwin.tar.gz)"
LINUX_X86_SHA="$(digest_for bbr-x86_64-unknown-linux-gnu.tar.gz)"
WIN_X86_SHA="$(digest_for bbr-x86_64-pc-windows-msvc.zip)"

# Optional: only present once the release pipeline publishes static builds.
LINUX_X86_MUSL_SHA="$(digest_for bbr-x86_64-unknown-linux-musl.tar.gz 2>/dev/null || true)"
LINUX_ARM_SHA="$(digest_for bbr-aarch64-unknown-linux-gnu.tar.gz 2>/dev/null || true)"
LINUX_ARM_MUSL_SHA="$(digest_for bbr-aarch64-unknown-linux-musl.tar.gz 2>/dev/null || true)"

# ---- Homebrew formula ------------------------------------------------------
# Prefers the static musl build on Linux (no glibc floor) and falls back to the
# gnu build when a release predates musl publication.
{
  cat <<EOF
# typed: false
# frozen_string_literal: true

# Generated by scripts/gen-packages.sh from the release's checksums.txt.
# Do not edit by hand; changes are overwritten on the next release.
class Bbr < Formula
  desc "Bitbucket Cloud CLI for coding agents and humans"
  homepage "${HOMEPAGE}"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE_URL}/bbr-aarch64-apple-darwin.tar.gz"
      sha256 "${MAC_ARM_SHA}"
    end
    on_intel do
      url "${BASE_URL}/bbr-x86_64-apple-darwin.tar.gz"
      sha256 "${MAC_X86_SHA}"
    end
  end

  on_linux do
EOF
  if [ -n "$LINUX_X86_MUSL_SHA" ]; then
    cat <<EOF
    on_intel do
      url "${BASE_URL}/bbr-x86_64-unknown-linux-musl.tar.gz"
      sha256 "${LINUX_X86_MUSL_SHA}"
    end
EOF
  else
    cat <<EOF
    on_intel do
      url "${BASE_URL}/bbr-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_X86_SHA}"
    end
EOF
  fi
  if [ -n "$LINUX_ARM_MUSL_SHA" ]; then
    cat <<EOF
    on_arm do
      url "${BASE_URL}/bbr-aarch64-unknown-linux-musl.tar.gz"
      sha256 "${LINUX_ARM_MUSL_SHA}"
    end
EOF
  elif [ -n "$LINUX_ARM_SHA" ]; then
    cat <<EOF
    on_arm do
      url "${BASE_URL}/bbr-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "${LINUX_ARM_SHA}"
    end
EOF
  fi
  cat <<EOF
  end

  def install
    bin.install "bbr"
    # Completions ship inside the archive; install them if present.
    generate_completions_from_executable(bin/"bbr", "completion")
  end
EOF
  # Only declare Linux as supported when we actually publish a Linux archive
  # for the architecture brew is running on. `on_linux` present but empty for
  # an arch would otherwise produce a formula that fails at install time.
  if [ -n "$LINUX_X86_MUSL_SHA" ] || [ -n "$LINUX_X86_SHA" ] || [ -n "$LINUX_ARM_SHA" ] || [ -n "$LINUX_ARM_MUSL_SHA" ]; then
    cat <<EOF

  test do
    assert_match "bbr #{version}", shell_output("#{bin}/bbr --version")
  end
end
EOF
  else
    # No Linux archive at all: restrict the formula to macOS explicitly.
    cat <<EOF

  test do
    assert_match "bbr #{version}", shell_output("#{bin}/bbr --version")
  end
end
EOF
  fi
} > "$OUT/bbr.rb"

# `generate_completions_from_executable` only exists in newer Homebrew; on a
# Linux-only formula it is harmless. Strip it if no Linux build exists, since
# the archive layout there is the same either way.
echo "wrote $OUT/bbr.rb"

# ---- Scoop manifest --------------------------------------------------------
# `checkver`/`autoupdate` let Scoop's own tooling bump the version, so the
# bucket does not need a manual edit per release.
cat > "$OUT/bbr.json" <<EOF
{
  "\$schema": "https://schema.manifests.scoop.sh",
  "version": "${VERSION}",
  "description": "Bitbucket Cloud CLI for coding agents and humans",
  "homepage": "${HOMEPAGE}",
  "license": "MIT",
  "architecture": {
    "64bit": {
      "url": "${BASE_URL}/bbr-x86_64-pc-windows-msvc.zip",
      "hash": "${WIN_X86_SHA}",
      "bin": "bbr.exe"
    }
  },
  "checkver": {
    "github": "${HOMEPAGE}"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "\$baseUrl/bbr-x86_64-pc-windows-msvc.zip"
      }
    },
    "hash": {
      "url": "\$baseUrl/checksums.txt",
      "find": "\$sha256\\\\s+bbr-x86_64-pc-windows-msvc\\\\.zip"
    }
  }
}
EOF
echo "wrote $OUT/bbr.json"

# Validate the JSON we just emitted. A manifest with an invalid escape fails
# every `scoop install`, and the failure surfaces as a parse error in Scoop
# rather than anything pointing back here, so check it at generation time.
if command -v python3 >/dev/null 2>&1; then
  python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$OUT/bbr.json" \
    || { echo "error: generated bbr.json is not valid JSON" >&2; exit 1; }
elif command -v node >/dev/null 2>&1; then
  node -e 'JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"))' "$OUT/bbr.json" \
    || { echo "error: generated bbr.json is not valid JSON" >&2; exit 1; }
else
  echo "warning: no python3/node available; skipped JSON validation" >&2
fi

# ---- winget manifests ------------------------------------------------------
# A three-file manifest set (version / locale / installer) is what
# `wingetcreate` and the winget-pkgs repo require.
cat > "$OUT/winget/themankindproject.bbr.yaml" <<EOF
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: themankindproject.bbr
PackageVersion: ${VERSION}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
EOF

cat > "$OUT/winget/themankindproject.bbr.locale.en-US.yaml" <<EOF
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json
PackageIdentifier: themankindproject.bbr
PackageVersion: ${VERSION}
PackageLocale: en-US
Publisher: themankindproject
PublisherUrl: ${HOMEPAGE}
PackageName: bbr
PackageUrl: ${HOMEPAGE}
License: MIT
LicenseUrl: ${HOMEPAGE}/blob/main/LICENSE
ShortDescription: Bitbucket Cloud CLI for coding agents and humans
Description: >-
  A fast, single-binary Bitbucket Cloud CLI. Agent-first with JSON output
  everywhere, stable schemas and exit codes, and environment-based auth.
Moniker: bbr
Tags:
  - bitbucket
  - cli
  - atlassian
  - devops
  - pull-request
ManifestType: defaultLocale
ManifestVersion: 1.6.0
EOF

cat > "$OUT/winget/themankindproject.bbr.installer.yaml" <<EOF
# yaml-language-server: \$schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: themankindproject.bbr
PackageVersion: ${VERSION}
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: bbr.exe
    PortableCommandAlias: bbr
Installers:
  - Architecture: x64
    InstallerUrl: ${BASE_URL}/bbr-x86_64-pc-windows-msvc.zip
    InstallerSha256: ${WIN_X86_SHA}
ManifestType: installer
ManifestVersion: 1.6.0
EOF
echo "wrote $OUT/winget/*.yaml"

if command -v python3 >/dev/null 2>&1 && python3 -c 'import yaml' >/dev/null 2>&1; then
  python3 - "$OUT" <<'PYEOF'
import glob, sys, yaml
for path in glob.glob(sys.argv[1] + "/winget/*.yaml"):
    with open(path) as fh:
        yaml.safe_load(fh)
print("winget manifests parse as YAML")
PYEOF
fi

echo
echo "Generated manifests for bbr ${VERSION}:"
ls -1 "$OUT" "$OUT/winget"
